name: Keep Render Backend Awake

on:
  schedule:
    - cron: "*/8 * * * *"
  workflow_dispatch:

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render API Endpoint
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://sightmate.onrender.com/api/test
